image: ubuntu:22.04

pages:
  before_script:
    - apt-get update && apt-get install -y pandoc curl

  script:
    - mkdir -p public
    - pandoc -s README.md -o public/index.html --css=style.css
    - cp style.css public/
    - cp -r assets public/

  artifacts:
    paths:
      - public