image: ubuntu:22.04

pages:
  before_script:
    - apt-get update && apt-get install -y pandoc curl

  script:
    # Make target folders
    - mkdir -p public

    # Convert root README.md to HTML at /
    - pandoc README.md -o public/index.html

    - rsync -a --exclude=public ./ public/ || true

  artifacts:
    paths:
      - public