image: ubuntu:22.04

pages:
  before_script:
    - apt-get update && apt-get install -y pandoc curl

  script:
    # Convert root README.md to HTML
    - pandoc README.md -o /index.html

  artifacts:
    paths:
      - .